config/routes.rb
Sepol::Application.routes.draw do
  resources :publicacoes do
    collection do
      get :buscar
    end
  end

  resources :equipamentos

  resources :reservas do
    collection do
      get :buscar
    end
  end
  resources :equipamentos do
    resources :reservas
    resources :reservas do
      resources :comentarios, only: [:index, :show, :create]
      resources :resultados
    end
  end

  devise_for :usuarios

  resources :home, only: [:index]
  resources :usuarios, only: [:index, :show]
  root to: 'home#index'

end

app/models/equipamento.rb
class Equipamento < ActiveRecord::Base
  has_many :reservas
  has_attached_file :imagem, :styles => { :medium => "800x600>", :thumb => "280x200#" }		
  
  validates_presence_of :nome, :descricao, :imagem

  attr_accessible :descricao, :nome, :imagem
  self.per_page = 4
end

app/controllers/equipamentos_controller.rb
class EquipamentosController < InheritedResources::Base
	load_and_authorize_resource
	def index
		@equipamentos = Equipamento.paginate(:page => params[:page])
	end

	def create
		create! notice: 'Equipamento criado com sucesso!'
	end
end

app/helpers/equipamentos_helper.rb
module EquipamentosHelper
end

app/views/equipamentos/_form.html.haml
=  semantic_form_for @equipamento do |f|
  - if @equipamento.errors.any?
    #error_explanation
      %h2= "#{pluralize(@equipamento.errors.count, "error")} prohibited this equipamento from being saved:"
      %ul
        - @equipamento.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :nome, label: 'Nome'
  .field
    = f.input :descricao, label: 'Descrição'
  .field
    = f.input :imagem
  .actions
    = f.submit 'Save'

app/views/equipamentos/edit.html.haml
%h1 Editar Equipamento

= render 'form'

= link_to 'Show', @equipamento
\|
= link_to 'Back', equipamentos_path

app/views/equipamentos/index.html.haml
.span.row
  %div.thumbnails
  -@equipamentos.each do |equipamento|  
    %div.span3.thumbnail
      %a{"data-toggle"=> "lightbox", :href=>"##{equipamento.id}"}
        %img{ src: root_url.chomp('/') + equipamento.imagem.url(:thumb)}
      %div{:id=> "#{equipamento.id}", :class=>"lightbox hide fade",  "tabindex" => "-1", "role" => "dialog", "aria-hidden" => "true"}
        %div{:class=>"lightbox-header"}
          %button{:type=>"button", :class=>"close", "data-dismiss"=>"lightbox", "aria-hidden"=>"true"}
            &times
        %div{:class=>"lightbox-content"}
          %div
            %img{:class=>"polaroid", :src=> root_url.chomp('/') + equipamento.imagem.url(:medium)}
          %div.lightbox-caption
            =equipamento.descricao
      %div.caption
        %h5
          =equipamento.nome[0..29]
      %p
        =equipamento.descricao
      -if usuario_signed_in?
        %hr
          =link_to raw('<i class="icon-time"></i> Reservar Equipamento'), new_equipamento_reserva_path(equipamento), class: "btn btn-large btn-block"

  %div.btn-group
    =will_paginate @equipamentos, container: false
  %a{class: "btn btn-small carousel-control left", "data-slide"=>"prev", onclick: "$(\".previous_page\").children()[0].click();"}
    = "‹"

  %a{class: "btn btn-small carousel-control right", "data-slide"=>"next", onclick: "$(\".next_page\").children()[0].click();"}
    = "›"

      
    

app/views/equipamentos/new.html.haml
%h1 Adicionar Equipamento

= render 'form'

= link_to 'Back', equipamentos_path

app/views/equipamentos/show.html.haml
%p#notice= notice


%p
	%b Nome:
	= @equipamento.nome

=image_tag @equipamento.imagem.url(:medium)

%p
	%b Descricao:
	= @equipamento.descricao

= link_to 'Edit', edit_equipamento_path(@equipamento)
\|
= link_to 'Back', equipamentos_path