config/routes.rb
Sepol::Application.routes.draw do
  resources :publicacoes do
    collection do
      get :buscar
    end
  end

  resources :equipamentos

  resources :reservas do
    collection do
      get :buscar
    end
  end
  resources :equipamentos do
    resources :reservas
    resources :reservas do
      resources :comentarios, only: [:index, :show, :create]
      resources :resultados
    end
  end

  devise_for :usuarios

  resources :home, only: [:index]
  resources :usuarios, only: [:index, :show]
  root to: 'home#index'

end

app/models/reserva.rb
#encoding: utf-8
class Reserva < ActiveRecord::Base
  belongs_to :usuario 
  belongs_to :equipamento
  has_many :comentarios
  has_one :resultado
  attr_accessible :horario_final, :horario_inicial, :usuario_id, :equipamento_id
  validates_presence_of :usuario_id, :equipamento_id, :horario_inicial, :horario_final
  validate :validar_horario
end

def validar_horario
  unless (self.horario_final and self.horario_inicial) == nil
    if self.horario_final < self.horario_inicial
      errors.add(:horario_inicial, "tem que ser anterior ao horario final.")
    end
    if self.horario_inicial == self.horario_final
      errors.add(:horario_final, "tem que ser maior que o horario inicial")
    end
  end
  @horarios_iniciais, @horarios_finais = [], []
  Reserva.where('equipamento_id = ?', self.equipamento_id).each{|reserva| @horarios_iniciais << reserva.horario_inicial; @horarios_finais << reserva.horario_final}
  @horarios_iniciais.zip(@horarios_finais).each do |inicio, fim| 
    if inicio.between?(self.horario_inicial, self.horario_final) or fim.between?(self.horario_inicial, self.horario_final)
      errors.add(:base, "Já existe uma reserva dentro desse intervalo de tempo")
      break
    end
  end
end

app/controllers/reservas_controller.rb
class ReservasController < InheritedResources::Base
	load_and_authorize_resource
	def index
		if params[:equipamento_id]
			if current_usuario.admin?
				@equipamento = Equipamento.find(params[:equipamento_id])
				@reservas = @equipamento.reservas
			else
				@equipamento = Equipamento.find(params[:equipamento_id])
				@reservas = current_usuario.reservas.where(equipamento_id: @equipamento.id)
			end
		else
			@reservas = current_usuario.reservas
		end
	end

	def new
		@equipamento = Equipamento.find(params[:equipamento_id])
		@reserva = @equipamento.reservas.build
	end

	def show
		@equipamento = Equipamento.find(params[:equipamento_id])
		@comentarios = Reserva.find(params[:id]).comentarios
		@reserva = Reserva.find params[:id]
		@comentario = @reserva.comentarios.build(autor: current_usuario.admin? ? 'Administrador' : current_usuario.nome)
	end

	def create
		@equipamento = Equipamento.find(params[:reserva][:equipamento_id])
		@reserva = @equipamento.reservas.build(params[:reserva])
		@reserva.save!
		redirect_to equipamentos_path, notice: "Reserva feita com sucesso."
	end

  def buscar
   	@equipamento = Equipamento.find(params[:equipamento])
		respond_to :js
  end
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/_descricao_imagem.html.haml
%div.span3
  %img{:class=>"img-polaroid", :src=> root_url.chomp('/') + equipamento.imagem.url(:medium)}
%div.span3
  =equipamento.descricao

app/views/reservas/_form.html.haml
%div.row
  %div.span5.well
    = semantic_form_for [@equipamento, @reserva] do |f|
      - if @reserva.errors.any?
        #error_explanation
          %h2= "#{pluralize(@reserva.errors.count, "error")} prohibited this reserva from being saved:"
          %ul
            - @reserva.errors.full_messages.each do |msg|
              %li= msg

      .field
        = f.label :Equipamento
        = f.select :equipamento_id,  Equipamento.all.map{|b| [b.nome, b.id]}, label: 'equipamento'

        = f.label :usuario
        = f.select :usuario_id, {current_usuario.nome => current_usuario.id}, label: 'usuario'


      .field
        %div.input-append{id: "datetimepicker_inicio"}
          =f.label :horario_inicial
          =f.text_field :horario_inicial, as: :string, label: 'Horario inicial', input_html: {id: "appendedInput", class: "span2", type: "text"}
          %span2.add-on
            %i{"data-time-icon"=>"icon-time", "data-date-icon"=>"icon-calendar"}


      .field
        %div.input-append{id: "datetimepicker_fim"}
          =f.label :horario_final
          =f.text_field :horario_final, as: :string, label: 'Horario inicial', input_html: {id: "appendedInput", class: "span2"}
          %span.add-on
            %i{"data-time-icon"=>"icon-time", "data-date-icon"=>"icon-calendar"}
      .actions
        = f.submit 'Save'

  %div.span7{id: "visualizacao-equipamento"}
    =render 'descricao_imagem', equipamento: @equipamento

app/views/reservas/_index_admin.html.haml
-if @equipamento
  %h5
    Todas as reservas para:
  %h3 
    =@equipamento.nome
    %hr

  %table.table.table-striped
    %tr
      %th Usuario
      %th Horario Inicio
      %th Horario Final
    -@reservas.sort_by(&:horario_inicial).each do |reserva|
      %tr
        %td 
          = reserva.usuario.nome
        %td 
          =link_to reserva.horario_inicial.strftime("%T - %D"), equipamento_reserva_path(@equipamento, reserva)
        %td 
          =reserva.horario_final.strftime("%T - %D")
-else


  %h3 
    Minhas Reservas
    %hr

  %table.table.table-striped
    %tr
      %th Equipamento
      %th Horario Inicio
      %th Horario Final
    -@reservas.sort_by(&:horario_inicial).each do |reserva|
      %tr
        %td 
          = link_to reserva.equipamento.nome, equipamento_reservas_path(reserva.equipamento)
        %td 
          =link_to reserva.horario_inicial.strftime("%T - %D"), equipamento_reserva_path(reserva.equipamento, reserva)
        %td 
          =reserva.horario_final.strftime("%T - %D")

app/views/reservas/_index_usuario.html.haml
-if @equipamento
  %h5
    Minhas reservas para:
  %h3 
    =@equipamento.nome
    %hr

  %table.table.table-striped
    %tr
      %th Horario Inicio
      %th Horario Final
    -@reservas.sort_by(&:horario_inicial).each do |reserva|
      %tr
        %td 
          =link_to reserva.horario_inicial.strftime("%T - %D"), equipamento_reserva_path(@equipamento, reserva)
        %td 
          =reserva.horario_final.strftime("%T - %D")
-else


  %h3 
    Minhas Reservas
    %hr

  %table.table.table-striped
    %tr
      %th Equipamento
      %th Horario Inicio
      %th Horario Final
    -@reservas.sort_by(&:horario_inicial).each do |reserva|
      %tr
        %td 
          = link_to reserva.equipamento.nome, equipamento_reservas_path(reserva.equipamento)
        %td 
          =link_to reserva.horario_inicial.strftime("%T - %D"), equipamento_reserva_path(reserva.equipamento, reserva)
        %td 
          =reserva.horario_final.strftime("%T - %D")

app/views/reservas/buscar.js.erb
$('#visualizacao-equipamento').html("<%= escape_javascript(render 'descricao_imagem', equipamento: @equipamento) %>");

app/views/reservas/index.html.haml
-if current_usuario.admin?
	= render 'index_admin'
-else
	= render 'index_usuario'

app/views/reservas/new.html.haml
%div.offset
  %h3 Nova Reserva

  = render 'form'

  = link_to 'Back', equipamento_reservas_path(@equipamento)

app/views/reservas/show.html.haml
%div.tabbable
	%ul.nav.nav-tabs
		%li.active
			%a{href: '#lA', "data-toggle" => 'tab'}
				%b
					Detalhes
		%li
			%a{href: '#lB', "data-toggle" => 'tab'}
				%b
					Comentários

		%li
			%a{href: '#lC', "data-toggle" => 'tab'}
				%b
					Resultados


	%div.tab-content
		%div.tab-pane.active{id: "lA"}
			%h5 Equipamento:
			%p	
				=@reserva.equipamento.nome

			%h5 Requerente
			%p
				%b 
					Nome:
				=@reserva.usuario.nome

			%h5 Horario Reserva

			%p
				%b
					inicio:
				=@reserva.horario_inicial.strftime("%D - %T")
			%p
				%b
					fim:
				=@reserva.horario_final.strftime("%D - %T")
			%hr



		%div.tab-pane{id: "lB"}
			%div.scroll
				%dl.dl-horizontal
					-@comentarios.each do |comentario|
						%dt
							=comentario.autor + ':'
						%dd.span6.well.well-small
							=comentario.texto

			= semantic_form_for [@reserva, @comentario], url: equipamento_reserva_comentarios_path(@reserva.equipamento, @reserva, @comentario) do |f|
				%dl
					%dt
						=f.input :autor, as: :select, collection: [@comentario.autor], label: false, include_blank: false
	
					%dd
						= f.input :texto, as: :text, label: 'comentario', :input_html =>{ class: 'span7', rows: 5}
					%div.span5.pull-right
						= f.submit 'Enviar'

		%div.tab-pane{id: "lC"}	
			-if @reserva.resultado.nil?
				%h5 Ainda não há resultado disponível
			-else
				%img{class: "img-rounded", src: root_url.chomp('/') + @reserva.resultado.imagem.url(:medium)}