config/routes.rb
Sepol::Application.routes.draw do
  resources :publicacoes do
    collection do
      get :buscar
    end
  end

  resources :equipamentos

  resources :reservas do
    collection do
      get :buscar
    end
  end
  resources :equipamentos do
    resources :reservas
    resources :reservas do
      resources :comentarios, only: [:index, :show, :create]
      resources :resultados
    end
  end

  devise_for :usuarios

  resources :home, only: [:index]
  resources :usuarios, only: [:index, :show]
  root to: 'home#index'

end

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
	%div{:class => "alert " + twitterized_type(type) }
		%button.close{:href => "#", "data-dismiss"=> "alert"} &times
		%b
			=message

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Sepol"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag :defaults
    = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    =render :partial => "layouts/flash_messages", :locals => {:flash => flash}

    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %p.nav.brand
            Sepol
          .container.nav-collapse
            %ul.nav
              %li
                %a{href: root_path}
                  %i.icon-home
                  Home
              -if usuario_signed_in?
                %li
                  %a{href: usuario_path(current_usuario)}
                    %i.icon-user
                    Perfil
              %li
                %a{href: usuarios_path}
                  %i.icon-group
                  Grupo de Pesquisa
              %li
                %a{href: equipamentos_path}
                  %i.icon-beaker
                  Equipamentos
              %li
                %a{href: publicacoes_path}
                  %i.icon-book
                  Publicações
            %ul.nav.pull-right
              - if usuario_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    =current_usuario.email
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to "Editar", edit_usuario_registration_path
                    %li= link_to "Sair", destroy_usuario_session_path
              - else
                %li= link_to('Entrar', new_usuario_session_path)

    .container-fluid
      = yield

    %footer
      %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"